server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1200

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/blogdbjpa?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jang6955
    driver-class-name: org.mariadb.jdbc.Driver
  messages:
    basename: errors


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type : trace
